### PR TITLE
Replacing old execSync with Node 0.12 native feature

### PR DESCRIPTION
**Pull request by igorsantos07**
I guess it should be noted somewhere that it's only supported now on Node 0.12+. [That's when it started supporting execSync natively](https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/).

### CODE REVIEW

**Comment by igorsantos07** [comment]
I could not run tests locally tho. It seems there was a lot of issues with paths and requires :|

**Comment by igorsantos07** [comment]
This is what I had to do to have tests working locally again (running io.js 1.6.4):

``` diff
diff --git a/Makefile b/Makefile
index db0f4a2..f9e68d9 100644
--- a/Makefile
+++ b/Makefile
@@ -1,11 +1,10 @@
 NODE_LIBS=NODE_PATH=.:./lib/:$(NODE_PATH)
-NODE_EXEC=$(NODE_LIBS) ./node_modules/.bin/

 console:
    $(NODE_LIBS) node

 test: .PHONY
-   $(NODE_EXEC)nodeunit ./test/*_test.js
+   ./node_modules/nodeunit/bin/nodeunit ./test/*_test.js

 functional:
    $(NODE_LIBS) node ./test/functional.js
diff --git a/test/phapper_test.js b/test/phapper_test.js
index e533299..792696e 100644
--- a/test/phapper_test.js
+++ b/test/phapper_test.js
@@ -1,4 +1,4 @@
-var Phapper = require('lib/phapper');
+var Phapper = require('../lib/phapper');

 module.exports = {
     setUp: function(cb) {
```

**Comment by jmervine** [comment]
What I worry about here is backwards compatibility with 0.10.x. I'm thinking because it's a dev/test tool primarily, perhaps saying screw it, but I'm not 100% sure. Thanks for the PR, I'll merge when I'm ready to release, which I don't have time for this week.

**Comment by jmervine** [comment]
Note to self: 

Considering trying [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) to include exec-sync (for sub 0.12 versions) with checks (maybe via try) for native execSync, falling back to the external method and better error messaging otherwise.

**Comment by igorsantos07** [comment]
I say that, if the guy is stuck on 0.10, keep the old version.
This PR does not includes new features. It's just a version update so who's
using new versions of Node are free to use it.
This Node version details could be noted down on the current release readme
and in the new release readme :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by jmervine** [comment]
Merged manually, tweaked a few things (unrelated to your changes really) and bumped the version to 0.2.1. Enjoy and thanks for your help.

**Comment by jmervine** [comment]
@igorsantos07 ^^

**Comment by igorsantos07** [comment]
thanks man! I've been quite busy but didn't forget this!

**Comment by davidsonfellipe** [comment]
@igorsantos07 @jmervine thanks you so much! I'll create a new release with this update.

**Pull request closed without merging**
